### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by Akbar-arm** [nsdrude-varigit/meta-variscite-sdk-imx#1]
There is no overall LICENSE file in this layer. Is it possible to list all the licenses that are used by recipes in this layer?

**Comment by nsdrude** [comment]
@Akbar-arm this is not the official meta-variscite-sdk repository. Please see https://github.com/varigit/meta-variscite-sdk/commit/efea67d3247a1201ae25a7e9d09f5434ac70f813
